// Centralized data for Results, Admit Cards, and Answer Keys
const updatesData = [
  // RESULTS
  { id: 1, type: "result", title: "JEE Main Session 2 Result 2026", date: "Declared: 24 Apr 2026", link: "https://jeemain.nta.ac.in/" },
  { id: 2, type: "result", title: "MP Board 10th & 12th Result 2026", date: "Declared: 24 Apr 2026", link: "https://mpresults.nic.in/" },
  { id: 3, type: "result", title: "UP Board 10th Result 2026", date: "Declared: 20 Apr 2026", link: "https://upresults.nic.in/" },
  { id: 4, type: "result", title: "UP Board 12th Result 2026", date: "Declared: 20 Apr 2026", link: "https://upresults.nic.in/" },
  { id: 5, type: "result", title: "UPSC CSE Final Result 2026", date: "Declared: 16 Apr 2026", link: "https://upsc.gov.in/" },
  { id: 6, type: "result", title: "IBPS PO Final Result 2026", date: "Declared: 01 Apr 2026", link: "https://ibps.in/" },
  { id: 7, type: "result", title: "IBPS Clerk Final Result 2026", date: "Declared: 01 Apr 2026", link: "https://ibps.in/" },
  { id: 8, type: "result", title: "Bihar Board 10th Result 2026", date: "Declared: 31 Mar 2026", link: "https://results.biharboardonline.com/" },
  { id: 9, type: "result", title: "Bihar Board 12th Result 2026", date: "Declared: 23 Mar 2026", link: "https://results.biharboardonline.com/" },
  { id: 10, type: "result", title: "SBI PO Final Result 2026", date: "Declared: 19 Mar 2026", link: "https://sbi.co.in/web/careers" },
  { id: 11, type: "result", title: "SSC CGL Tier 2 Result 2026", date: "Declared: 04 Mar 2026", link: "https://ssc.gov.in/" },
  { id: 12, type: "result", title: "CTET Result 2026", date: "Declared: 15 Feb 2026", link: "https://ctet.nic.in/" },
  { id: 13, type: "result", title: "SSC GD Constable Final Result 2026", date: "Latest Available", link: "https://ssc.gov.in/" },
  { id: 14, type: "result", title: "RRB Group D Final Result 2026", date: "Latest Available", link: "https://rrbcdg.gov.in/" },
  { id: 15, type: "result", title: "RRB NTPC CBT 1 Result 2026", date: "Latest Available", link: "https://rrbcdg.gov.in/" },
  { id: 16, type: "result", title: "SBI Clerk Mains Result 2026", date: "Latest Available", link: "https://sbi.co.in/web/careers" },
  { id: 17, type: "result", title: "NEET UG Result 2026", date: "Latest Available", link: "https://exams.nta.ac.in/NEET/" },
  { id: 18, type: "result", title: "UGC NET Final Result 2026", date: "Latest Available", link: "https://ugcnet.nta.nic.in/" },
  { id: 19, type: "result", title: "India Post GDS Merit List 2026", date: "Latest Available", link: "https://indiapostgdsonline.gov.in/" },
  { id: 20, type: "result", title: "UP Police Constable Final Result 2026", date: "Latest Available", link: "https://uppbpb.gov.in/" },

  // ADMIT CARDS
  { id: 21, type: "admit", title: "UPSC Civil Services Prelims Admit Card 2026", date: "Available: May 2026", link: "https://upsconline.nic.in/" },
  { id: 22, type: "admit", title: "RRB NTPC CBT 1 Admit Card 2026", date: "Released: 03 May 2026", link: "https://rrbcdg.gov.in/" },
  { id: 23, type: "admit", title: "SSC Selection Post Phase XIV Admit Card 2026", date: "Available: May 2026", link: "https://ssc.gov.in/" },
  { id: 24, type: "admit", title: "Indian Navy Agniveer SSR Admit Card 2026", date: "Released: 01 May 2026", link: "https://joinindiannavy.gov.in/" },
  { id: 25, type: "admit", title: "MPESB PAT (Pre Agriculture Test) Admit Card 2026", date: "Released: 01 May 2026", link: "https://esb.mp.gov.in/" },
  { id: 26, type: "admit", title: "NEET UG Admit Card 2026", date: "Released: 26 Apr 2026", link: "https://exams.nta.ac.in/NEET/" },
  { id: 27, type: "admit", title: "CUET UG City Intimation Slip 2026", date: "Released: 29 Apr 2026", link: "https://cuet.nta.nic.in/" },
  { id: 28, type: "admit", title: "CUET UG Admit Card 2026", date: "Available: May 2026", link: "https://cuet.nta.nic.in/" },
  { id: 29, type: "admit", title: "UP Police Constable Re-Exam Admit Card 2026", date: "Available: May 2026", link: "https://uppbpb.gov.in/" },
  { id: 30, type: "admit", title: "SSC CHSL Tier 1 Admit Card 2026", date: "Available: May 2026", link: "https://ssc.gov.in/" },
  { id: 31, type: "admit", title: "SBI Clerk Mains Admit Card 2026", date: "Available: May 2026", link: "https://sbi.co.in/web/careers" },
  { id: 32, type: "admit", title: "IBPS PO Interview Call Letter 2026", date: "Available: May 2026", link: "https://ibps.in/" },
  { id: 33, type: "admit", title: "BPSC TRE 3.0 Admit Card 2026", date: "Available: May 2026", link: "https://bpsc.bih.nic.in/" },
  { id: 34, type: "admit", title: "UPSC NDA & NA I Admit Card 2026", date: "Released: Apr 2026", link: "https://upsconline.nic.in/" },
  { id: 35, type: "admit", title: "UPSC CDS I Admit Card 2026", date: "Released: Apr 2026", link: "https://upsconline.nic.in/" },

  // ANSWER KEYS
  { id: 41, type: "answer", title: "UPSC NDA 1 Answer Key 2026", date: "Available: May 2026", link: "https://upsc.gov.in/" },
  { id: 42, type: "answer", title: "UPSC CDS 1 Answer Key 2026", date: "Available: May 2026", link: "https://upsc.gov.in/" },
  { id: 43, type: "answer", title: "UP Police Constable Re-Exam Answer Key 2026", date: "Available: May 2026", link: "https://uppbpb.gov.in/" },
  { id: 44, type: "answer", title: "BPSC TRE 3.0 Answer Key 2026", date: "Available: May 2026", link: "https://bpsc.bih.nic.in/" },
  { id: 45, type: "answer", title: "MPESB Constable Final Answer Key 2026", date: "Available: May 2026", link: "https://esb.mp.gov.in/" },
  { id: 46, type: "answer", title: "SBI Clerk Mains Answer Key 2026", date: "Available: May 2026", link: "https://sbi.co.in/web/careers" },
  { id: 47, type: "answer", title: "DSSSB Various Post Answer Key 2026", date: "Available: May 2026", link: "https://dsssb.delhi.gov.in/" },
  { id: 48, type: "answer", title: "Haryana Police Constable Answer Key 2026", date: "Available: May 2026", link: "https://hssc.gov.in/" },
  { id: 49, type: "answer", title: "SSC CHSL Tier 2 Answer Key 2026", date: "Released: 20 Apr 2026", link: "https://ssc.gov.in/" },
  { id: 50, type: "answer", title: "UPSSSC ANM Final Answer Key 2026", date: "Released: 16 Apr 2026", link: "https://upsssc.gov.in/" },
  { id: 51, type: "answer", title: "CUET PG Final Answer Key 2026", date: "Released: Apr 2026", link: "https://cuet.nta.nic.in/" },
  { id: 52, type: "answer", title: "JEE Main Session 2 Answer Key 2026", date: "Released: Apr 2026", link: "https://jeemain.nta.ac.in/" },
  { id: 53, type: "answer", title: "RRB NTPC CBT 1 Answer Key 2026", date: "Released: 06 Apr 2026", link: "https://rrbcdg.gov.in/" },
  { id: 54, type: "answer", title: "RRB Group D Answer Key 2026", date: "Released: 17 Feb 2026", link: "https://rrbcdg.gov.in/" },
  { id: 55, type: "answer", title: "SSC CGL Tier 2 Answer Key 2026", date: "Released: 30 Jan 2026", link: "https://ssc.gov.in/" }
];
